--1
SELECT ACT_FIRSTNAME, ACT_LASTNAME, DIR_FIRSTNAME, DIR_LASTNAME
FROM ACTOR, DIRECTOR WHERE ACT_FIRSTNAME = DIR_FIRSTNAME AND ACT_LASTNAME = DIR_LASTNAME;

--2
SELECT ACT_FIRSTNAME, COUNT(*) AS NUM_ACTRESS
FROM ACTOR
WHERE ACT_GENDER = 'F'
GROUP BY ACT_FIRSTNAME
HAVING COUNT(*)>1;

--3
SELECT ACT_FIRSTNAME || ' ' || ACT_LASTNAME AS FULL_NAME
FROM ACTOR
UNION
SELECT DIR_FIRSTNAME || ' ' || DIR_LASTNAME AS FULL_NAME
FROM DIRECTOR;

--4
SELECT MOV_TITLE FROM MOVIE
WHERE MOV_ID NOT IN (
    SELECT MOV_ID
    FROM RATING
);

--5
SELECT AVG(REV_STARS) AS AVERAGE_RATING
FROM RATING;

--6
SELECT MOV_ID, MIN(REV_STARS) AS MINIMUM_RATING
FROM RATING
GROUP BY MOV_ID
ORDER BY MINIMUM_RATING DESC;

--7
SELECT MOV_TITLE
FROM MOVIE
WHERE MOV_ID IN (
    SELECT MOV_ID
    FROM RATING
    GROUP BY MOV_ID
    HAVING AVG(REV_STARS) > (SELECT AVG(REV_STARS) FROM RATING)
);

--8
SELECT ACT_FIRSTNAME, ACT_LASTNAME, COUNT(*) AS RATINGS
FROM ACTOR, CASTS, RATING
WHERE ACTOR.ACT_ID = CASTS.ACT_ID AND CASTS.MOV_ID = RATING.MOV_ID
GROUP BY ACT_FIRSTNAME, ACT_LASTNAME
ORDER BY RATINGS DESC;

--9
SELECT DIR_NAME, AVG_RATING FROM
(   
    SELECT D.DIR_FIRSTNAME || ' ' || D.DIR_LASTNAME AS DIR_NAME,
    (
        SELECT avg(R.REV_STARS)
        FROM RATING R
        WHERE R.MOV_ID IN
        (
            SELECT DN.MOV_ID
            FROM DIRECTION DN
            WHERE DN.DIR_ID = D.DIR_ID
        )
        AND R.REV_STARS IS NOT NULL
    ) AS AVG_RATING
    FROM DIRECTOR D
    WHERE DIR_ID IN
    (
        SELECT DIR_ID FROM DIRECTION DN2
        WHERE DN2.MOV_ID IN
        (
            SELECT MOV_ID FROM RATING
        )
    )
    ORDER BY AVG_RATING DESC
)
WHERE ROWNUM = 1;

--10
SELECT *
FROM MOVIE 
WHERE MOV_ID
IN
(
    SELECT DN.MOV_ID
    FROM DIRECTION DN
    WHERE DN.DIR_ID
    IN
    (
        SELECT D.DIR_ID
        FROM DIRECTOR D
        WHERE D.DIR_FIRSTNAME || ' ' || D.DIR_LASTNAME
        IN
        (
            SELECT D1.DIR_FIRSTNAME || ' ' || D1.DIR_LASTNAME AS DIR_NAME1
            FROM DIRECTOR D1
            INTERSECT
            SELECT A.ACT_FIRSTNAME || ' ' || A.ACT_LASTNAME AS ACT_NAME
            FROM ACTOR A
        )
    )
);

--11
SELECT M.MOV_TITLE,
(
    SELECT avg(R.REV_STARS)
    FROM RATING R
    WHERE R.MOV_ID = M.MOV_ID
    AND R.REV_STARS IS NOT NULL
) AS AVG_RATE
FROM MOVIE M
WHERE M.MOV_ID
IN
(
    SELECT R1.MOV_ID
    FROM RATING R1
    WHERE R1.REV_STARS IS NOT NULL
    GROUP BY R1.MOV_ID
    HAVING avg(R1.REV_STARS) > 7
)
ORDER BY AVG_RATE DESC;

--12
SELECT R.REV_NAME
FROM REVIEWER R
WHERE R.REV_ID
IN
(
    SELECT RT.REV_ID
    FROM RATING RT
    WHERE RT.REV_STARS = 
    (
        SELECT min(REV_STARS)
        FROM RATING
    )
);

--13
SELECT A.ACT_FIRSTNAME || ' ' ||A.ACT_LASTNAME AS ACT_NAME,
(
    SELECT avg(M.MOV_TIME)
    FROM MOVIE M
    WHERE M.MOV_ID 
    IN
    (
        SELECT C.MOV_ID
        FROM CASTS C
        WHERE C.ACT_ID = A.ACT_ID
    )
    AND M.MOV_TIME IS NOT NULL
) AS AVG_RUNTIME
FROM ACTOR A
WHERE A.ACT_ID
IN
(
    SELECT ACT_ID FROM CASTS
)
AND A.ACT_ID 
NOT IN
(
    SELECT C2.ACT_ID
    FROM CASTS C2
    WHERE C2.MOV_ID
    IN
    (
        SELECT DN.MOV_ID
        FROM DIRECTION DN
        WHERE DN.DIR_ID =
        (
            SELECT DR.DIR_ID
            FROM DIRECTOR DR
            WHERE DR.DIR_FIRSTNAME = 'James' AND DR.DIR_LASTNAME = 'Cameron'
        )
    )
)
ORDER BY ACT_NAME;
















