-- Create DOCTOR table
CREATE TABLE DOCTOR (
    NAME VARCHAR2(20),
    SPECIALIZATION CHAR(2),
    FEE NUMBER,
    PRIMARY KEY (NAME, SPECIALIZATION)
);

-- Create PATIENT table
CREATE TABLE PATIENT (
    PATIENT_NO CHAR(5) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(10)
);

-- Create APPOINTMENT table
CREATE TABLE APPOINTMENT (
    PATIENT_NO CHAR(5),
    NAME VARCHAR2(20),
    SPECIALIZATION CHAR(2),
    PRIMARY KEY (PATIENT_NO, NAME, SPECIALIZATION),
    FOREIGN KEY (NAME, SPECIALIZATION) REFERENCES DOCTOR(NAME, SPECIALIZATION)
);
